{{- if .Values.obbyircd.enabled -}}
{{- range $name, $cfg := .Values.obbyircd.persistence }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "obby.fullname" $ }}-obbyircd-{{ $name | kebabcase }}
  labels:
    {{- include "obby.componentLabels" (dict "component" "obbyircd" "Release" $.Release "Chart" $.Chart "Values" $.Values) | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ $cfg.size }}
  {{- if $cfg.storageClass }}
  storageClassName: {{ $cfg.storageClass | quote }}
  {{- end }}
{{- end }}
{{- end }}
