{{- if .Values.obbyircd.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obby.fullname" . }}-obbyircd
  labels:
    {{- include "obby.componentLabels" (dict "component" "obbyircd" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
type: Opaque
stringData:
  OPER_PASSWORD: {{ .Values.obbyircd.operPassword | quote }}
  CLOAK_KEY1: {{ .Values.obbyircd.cloakKey1 | quote }}
  CLOAK_KEY2: {{ .Values.obbyircd.cloakKey2 | quote }}
  CLOAK_KEY3: {{ .Values.obbyircd.cloakKey3 | quote }}
  RPC_PASSWORD: {{ .Values.obbyircd.rpcPassword | quote }}
{{- end }}
{{- if .Values.obbyApi.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "obby.fullname" . }}-obby-api
  labels:
    {{- include "obby.componentLabels" (dict "component" "obby-api" "Release" .Release "Chart" .Chart "Values" .Values) | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.obbyApi.jwtSecret | quote }}
  IRC_SERVER_KEY: {{ .Values.obbyApi.ircServerKey | quote }}
  VOICE_TURN_SECRET: {{ .Values.obbyApi.turnSecret | quote }}
  UNREALIRCD_API_PASSWORD: {{ .Values.obbyircd.rpcPassword | quote }}
{{- end }}
