apiVersion: v2
name: obby
description: Obby IRC stack -- obbyircd + obby-api + web client
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - irc
  - obby
  - unrealircd
  - chat
home: https://github.com/obbyworld
sources:
  - https://github.com/obbyworld/ObbyIRCd
  - https://github.com/obbyworld/hosted-backend
  - https://github.com/obbyworld/obby
  - https://github.com/obbyworld/obby-stack
maintainers:
  - name: obbyworld
